# Generated by Django 5.2 on 2025-04-18 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('downline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upline', to=settings.AUTH_USER_MODEL)),
                ('upline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('upline', 'downline')},
            },
        ),
    ]
